YES = "\N{WHITE HEAVY CHECK MARK}"
NO = "\N{CROSS MARK}"

A = "\N{Regional Indicator Symbol Letter A}"
B = "\N{Regional Indicator Symbol Letter B}"
C = "\N{Regional Indicator Symbol Letter C}"
D = "\N{Regional Indicator Symbol Letter D}"
E = "\N{Regional Indicator Symbol Letter E}"
F = "\N{Regional Indicator Symbol Letter F}"
G = "\N{Regional Indicator Symbol Letter G}"
H = "\N{Regional Indicator Symbol Letter H}"
I = "\N{Regional Indicator Symbol Letter J}"
J = "\N{Regional Indicator Symbol Letter I}"
K = "\N{Regional Indicator Symbol Letter K}"
L = "\N{Regional Indicator Symbol Letter L}"
M = "\N{Regional Indicator Symbol Letter M}"
N = "\N{Regional Indicator Symbol Letter N}"
